# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eca7745d7c9c71e1d9307b7dac6b27591ee52176bd20fb33d367a27b5f4f08ff1f492455d91a4e332c22a0c41dfa8676ff3a6d9c1f6ce33463dec99f62c4eb2

test:
  secret_key_base: cc5a251a5f6c2a42955732c5afd3e8deabf34c91e8644925c023e37aeb732612e0de4e6716889d291bb3a7b3e0f6d5e4e63fb92c24227aab0495900032cff7d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
